{
  nodeQuery (limit:10, filter:{type:"article"}) {
    entities {
      title: entityLabel
      uid: entityUuid
      created: entityCreated
      url: entityUrl {
        path
      }
      ...on NodeArticle {
        body{summary}
        fieldImage {
          derivative(style:medium) {
            url
          }
        }
        fieldTags {
          entity{name}
        }
      }
    }
    count
  }
}
