{
  nodeQuery (limit:10, offset:0, filter:{type:"article"}) {
    entities {
      title: entityLabel
      uid: entityUuid
      url: entityUrl {
        path
      }
      ...on NodeArticle {
        body{processed}
        fieldImage {
          derivative(style:thumbnail) {
            url
          }
        }
        fieldTags {
          entity{name}
        }
      }
    }
    count
  }
}
