{
  nodeQuery(limit:10, offset:0, filter:{type:"article"}) {
    entities{
      entityLabel
      entityUrl {
        path
      }
      ...on NodeArticle {
        body
        fieldImage {
          derivative(style:thumbnail) {
            url
          }
        }
        fieldTags {
          entityLabel
        }
      }
    }
    count
  }
}